"""Companion — generate AI writing companion spec from all pipeline outputs."""
import json
from pathlib import Path
from datetime import datetime

from rich.console import Console

console = Console()


def load_json(path: Path) -> dict | list | None:
    if path.exists():
        return json.loads(path.read_text())
    return None


def load_text(path: Path) -> str | None:
    if path.exists():
        return path.read_text()
    return None


def run_companion(source: Path, output: Path, client_name: str):
    """Generate an AI writing companion from all pipeline outputs."""
    console.print(f"\n[bold]Prufrock Companion[/bold] — building AI writing partner for {client_name}\n")

    output.mkdir(parents=True, exist_ok=True)
    prufrock_dir = source / "prufrock-output"
    deliverable_dir = prufrock_dir / "deliverable"

    # Load all available data
    voice_profile = None
    for vp_path in [
        prufrock_dir / "voice" / "voice-profile.json",
        *prufrock_dir.rglob("voice-profile.json"),
    ]:
        voice_profile = load_json(vp_path)
        if voice_profile:
            break

    face_clusters = None
    for fp in [prufrock_dir / "faces" / "face-clusters.json", *prufrock_dir.rglob("face-clusters.json")]:
        face_clusters = load_json(fp)
        if face_clusters:
            break

    timeline_data = load_json(prufrock_dir / "timeline.json")
    threads = load_text(deliverable_dir / "memoir-threads.md") if deliverable_dir.exists() else None

    # Build the people section
    people_section = ""
    if face_clusters:
        named = [c for c in face_clusters.get("clusters", []) if c.get("name")]
        if named:
            people_lines = []
            for c in named:
                rel = c.get("relationship", "unknown relationship")
                notes = c.get("notes", "")
                people_lines.append(f"- **{c['name']}** ({rel}) — appears in {c['face_count']} photos. {notes}")
            people_section = "\n".join(people_lines)

    # Build timeline summary
    timeline_section = ""
    if timeline_data:
        years = sorted(set(d["date"][:4] for d in timeline_data))
        date_range = f"{timeline_data[0]['date']} to {timeline_data[-1]['date']}"
        timeline_section = (
            f"The archive spans {date_range} ({len(timeline_data)} documented events).\n"
            f"Years covered: {', '.join(years)}"
        )

    # Build voice instructions
    voice_section = ""
    if voice_profile:
        if "raw_analysis" in voice_profile:
            voice_section = voice_profile["raw_analysis"]
        else:
            parts = []
            for key in ["vocabulary_patterns", "sentence_structure", "storytelling_style",
                        "emotional_register", "anti_patterns"]:
                if key in voice_profile:
                    parts.append(f"### {key.replace('_', ' ').title()}\n{json.dumps(voice_profile[key], indent=2)}")
            voice_section = "\n\n".join(parts)

        stats = voice_profile.get("statistics", {})
        if stats:
            top_words = stats.get("top_distinctive_words", [])[:15]
            if top_words:
                voice_section += f"\n\n### Distinctive vocabulary\n{', '.join(w for w, _ in top_words)}"

    # Assemble the companion spec
    spec = f"""# {client_name} — AI Writing Companion
## Generated by Prufrock on {datetime.now().strftime('%B %d, %Y')}

---

## Your Role

You are a memoir writing companion for {client_name}. Your job is to help them
write their life story in THEIR voice — not yours. You are not a ghostwriter.
You are a mirror that reflects their words back in structured form.

**Core rules:**
- Write in {client_name}'s voice, using their vocabulary and sentence patterns
- Never invent events, people, or details not in the archive or conversation
- When they share a memory, help them expand it — ask about sensory details,
  who was there, what they felt, what they said
- Preserve their exact phrasing when it's distinctive
- If they circle a topic without landing on it, gently surface it:
  "You've mentioned [X] a few times — is there a story there?"
- Never analyze or interpret their trauma — let them tell it their way

---

## Family & People

{people_section or "*Complete face identification during the zoom session to populate this section.*"}

---

## Timeline

{timeline_section or "*Run the timeline command to populate this section.*"}

---

## Narrative Threads

{threads or "*Run the assemble command with an API key to generate thread analysis.*"}

---

## Voice Profile

{voice_section or "*Run the voice command on a recording to populate this section.*"}

---

## How to Use This Companion

### Option A: Claude (recommended)
1. Go to claude.ai
2. Start a new conversation
3. Paste this entire document as your first message
4. Say: "I'm ready to start writing. Ask me about [any thread above]."

### Option B: ChatGPT
1. Go to chat.openai.com
2. Create a Custom GPT with this as the system prompt
3. Start talking about your memories

### Option C: Voice
1. Use a voice-to-text app (Wispr, Google Voice, etc.)
2. Talk to the AI like you're on a phone call
3. It writes in your voice from your words

---

*Built with [Prufrock](https://github.com/NorthwoodsSentinel/prufrock) — Your life. Your voice. Your book.*
"""

    # Write companion spec
    spec_path = output / "companion-spec.md"
    spec_path.write_text(spec)

    # Also write a compact version for pasting into AI chat
    compact = spec.replace("---\n", "").strip()
    compact_path = output / "companion-paste.md"
    compact_path.write_text(compact)

    console.print(f"Companion spec: [bold]{spec_path}[/bold]")
    console.print(f"Paste-ready version: [bold]{compact_path}[/bold]")
    console.print(f"\nThe client can paste companion-paste.md into Claude or ChatGPT to start writing.\n")
